### ISSUE TITLE
Improving Footer Section UI

### ISSUE THREAD

**Issue by VishalGaurav01** [algovengers/MindMate#106]
Can use Flowbite to improve the footer UI
![Screenshot 2024-05-12 132236](https://github.com/algovengers/MindMate/assets/97465452/fb9a3b8a-4a5a-4c78-bef2-641d488bf3c8)
Assignee: Please Assign this issue to me. I m looking for some impactful contribution in this website

**Comment by subharthihazra** [comment]
issue #32 is on it.
