### ISSUE TITLE
Add copy text option in chat answer 

### ISSUE THREAD

**Issue by panam1916** [algovengers/MindMate#110]
![Copy_option](https://github.com/algovengers/MindMate/assets/92396633/95035a9e-bb0e-4bc2-9ea1-73c8048ef9a6)
I can Add copy text option on answer given by Ai

**Comment by subharthihazra** [comment]
Assigned to you.

**Comment by panam1916** [comment]
Thanks for assign it to me!

**Comment by panam1916** [comment]
Hi , my pr get merged but label not assign for it can you add label for my pr #139 that merged!!
