### ISSUE TITLE
build an about us page with the repository contribution list 

### ISSUE THREAD

**Issue by CoderSwarup** [algovengers/MindMate#112]
Currently, there's no section on our website that highlights the efforts and contributions of our repository contributors. This lack of visibility makes it difficult for new visitors to appreciate the collaborative efforts behind the project and see the history of contributions made by various team members.

please assign me this issue i want to work on this 

 example
![image](https://github.com/algovengers/MindMate/assets/128630311/721d1a0b-03aa-4b07-b786-65dd3c18d122)

**Comment by subharthihazra** [comment]
Assigned to you.
