### ISSUE TITLE
enchance: footer

### ISSUE THREAD

**Issue by devlohani99** [algovengers/MindMate#128]
![Screenshot 2024-05-24 011852](https://github.com/algovengers/MindMate/assets/142163543/179e94b9-e56f-4943-a09f-8c7401b34691)

footer need enhancement

**Comment by devlohani99** [comment]
@sanmarg @Sameer413 @subharthihazra  this is my first time in opensource contribution just give me a try !

**Comment by afeefuddin** [comment]
Duplicate #32
