### ISSUE TITLE
Footer : Open Youtube & Github in new Page 

### ISSUE THREAD

**Issue by mahak-juriani** [algovengers/MindMate#130]
<img width="572" alt="image" src="https://github.com/algovengers/MindMate/assets/135598205/24588ac3-fe4b-4c9b-a1f0-dbe880dfad40">

Youtube & Github open in the same page as the app.
We can open them in new page so the app continues to remain open

**Comment by mahak-juriani** [comment]
Please assign me under gssoc - would like to start contribution in this project, thanks

**Comment by afeefuddin** [comment]
Assigned @mahak-juriani

**Comment by Yash-Ainapure** [comment]
@afeefuddin ,
Can I contribute to it?
As the assigned user isn't active for past 3-4 days

**Comment by Vivekkaspa** [comment]
@afeefuddin , please assign me this issue. I am interested in contributing to this. I already have my task done.please assign me this so that I can make a PR. Thank you :)

**Comment by mahak-juriani** [comment]
@afeefuddin Please review, 
have raised PR https://github.com/algovengers/MindMate/pull/143
