### ISSUE TITLE
Remove logging email & password in console

### ISSUE THREAD

**Issue by mahak-juriani** [algovengers/MindMate#131]
<img width="327" alt="image" src="https://github.com/algovengers/MindMate/assets/135598205/c615f3b4-7c85-4a2b-b659-126d9e1764ac">

Remove logging email & password in console

**Comment by mahak-juriani** [comment]
Hi, Please assign this to me under gssoc, thanks

**Comment by afeefuddin** [comment]
Assigned @mahak-juriani

**Comment by Yash-Ainapure** [comment]
@afeefuddin ,
please assign me this issue, as the assigned user isn't active

**Comment by mahak-juriani** [comment]
I'll be raising pr for this case today have been active and working on other cases.

**Comment by mahak-juriani** [comment]
@afeefuddin Please review https://github.com/algovengers/MindMate/pull/144
