### ISSUE TITLE
[UI Enhancement] - Footer and Hero section design can be improvised.

### ISSUE THREAD

**Issue by NilanchalaPanda** [algovengers/MindMate#40]
The design of the Hero section and footer of the website can be enhanced and make appealing to the users.
I would love to work on this issue as a GSSoC'24 Contributor. Looking forward for your response.

IMAGE : 
![image](https://github.com/algovengers/MindMate/assets/110488337/c39635c0-519b-487b-ba74-286bf035d10e)

**Comment by afeefuddin** [comment]
Issue already exists #32

**Comment by NilanchalaPanda** [comment]
Okay @afeefuddin, thanks for the update. I totally missed it, my apologies.
