### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [algovengers/MindMate#45]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me, so i can work towards it.

**Comment by afeefuddin** [comment]
Sure go ahead.

**Comment by suhanipaliwal** [comment]
I have started working on this issue. Could you please label this issue under GSSOC'24 and also label an appropriate level like Level 1, 2 or 3. Thank you.
