### ISSUE TITLE
Validations using toastify library

### ISSUE THREAD

**Issue by Niharika0104** [algovengers/MindMate#53]
### Issue Description
**Summary:**
We currently have form validation implemented in our registration page, but we'd like to enhance the user experience by incorporating React Toastify for displaying validation messages.

**Expected Behavior:**
Form validation messages should be displayed using React Toastify, providing a more visually appealing and user-friendly way to convey validation errors.

**Current Behavior:**
Form validation messages are displayed within the form itself, which interrupts the layout and doesn't provide an optimal user experience.

### Steps to Reproduce
1. Navigate to the registration page.
2. Attempt to submit the form with invalid input.
3. Observe the current behavior of validation messages displayed within the form.

### Proposed Solution
Integrate React Toastify to handle form validation messages:
- Display validation messages using Toastify notifications.
- Ensure messages are clear and easy to understand.
- Customize Toastify appearance to match the overall design aesthetic.

### Additional Context
- Version of React being used.
- Any existing form validation libraries or mechanisms in place.
- Any specific requirements or constraints for the Toastify integration.

**Comment by subharthihazra** [comment]
Go ahead.
