### ISSUE TITLE
Improvement of footer design 

### ISSUE THREAD

**Issue by pradeepSDE** [algovengers/MindMate#60]
The footer looks can be improved by adding icons and images.
<img width="939" alt="image" src="https://github.com/algovengers/MindMate/assets/103747065/3505bad7-cff6-470d-bf05-a08f5ef1b0e3">
Please assign me this issue under Gssoc'24 so that I can work on  it

**Comment by pradeepSDE** [comment]
Iam interested in designing this to look good please assign this to me.

**Comment by afeefuddin** [comment]
Don't create duplicate issues. #32 already exists.
