### ISSUE TITLE
Changing the Button ui "chat with us..." on the Homepage

### ISSUE THREAD

**Issue by AkshatJain481** [algovengers/MindMate#67]
The cursor effect is text on the button "chat with us..." and there are no effects on hovering which isn't attractive. Change the UI of the button.

![image](https://github.com/algovengers/MindMate/assets/139246210/942cd7f3-430c-4080-91f5-83fb5f4526e3)

Please assign me this issue under the gssoc24 tag

**Comment by subharthihazra** [comment]
Issue #57 is already addressing it.
