### ISSUE TITLE
FOOTER  REDESIGN AND CONTACT US PAGE

### ISSUE THREAD

**Issue by NitinChakrawarti** [algovengers/MindMate#77]
@subharthihazra  Whole website is looking very nice but footer is not that much good,
and also in website contact us section is missing.

assign this issue to me i can redesign footer section and create responsive contact us page .

i want to work on this issue under GSSoC'24.

![Screenshot 2024-05-13 165502](https://github.com/algovengers/MindMate/assets/149225785/846d4416-e5eb-46cb-b9b7-19c80d2993a2)

**Comment by subharthihazra** [comment]
Issue #32 is on it.

**Comment by afeefuddin** [comment]
Closing Duplicated Issue.
